# Generated by Django 4.2.23 on 2025-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
            ],
            options={
                'permissions': [('can_view_book', 'Can View Book'), ('can_create_book', 'Can Create Book'), ('can_edit_book', 'Can Edit Book'), ('can_delete_book', 'Can Delete Book')],
            },
        ),
    ]
